### ISSUE TITLE
Sphinx build fail on Readthedocs

### ISSUE THREAD

**Issue by cdeil** [cdeil/healpix#4]
I'm currently getting this install error on Readthedocs:
http://readthedocs.org/projects/healpix/builds/4372160/

I'm currently trying to get it to work on Python 3 and pip (not conda) with access to global site-packages.

```
Running Sphinx v1.3.5
making output directory...
Fontconfig warning: ignoring C.UTF-8: not a valid language tag
Fontconfig warning: ignoring C.UTF-8: not a valid language tag

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/healpix/envs/latest/local/lib/python3.4/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/healpix/envs/latest/local/lib/python3.4/site-packages/sphinx/application.py", line 127, in __init__
    confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/healpix/envs/latest/local/lib/python3.4/site-packages/sphinx/config.py", line 277, in __init__
    execfile_(filename, config)
  File "/home/docs/checkouts/readthedocs.org/user_builds/healpix/envs/latest/local/lib/python3.4/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
    exec_(code, _globals)
  File "conf.py", line 88, in <module>
    __import__(setup_cfg['package_name'])
ImportError: No module named 'healpix'

Exception occurred:
  File "conf.py", line 88, in <module>
    __import__(setup_cfg['package_name'])
ImportError: No module named 'healpix'
The full traceback has been saved in /tmp/sphinx-err-popbw7zv.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

@bsipocz or @astrofrog - Have you seen this before? Any idea how to fix it?

**Comment by bsipocz** [comment]
@cdeil - I'm travelling, so probably won't be able to look at this in the
next few days.

**Comment by astrofrog** [comment]
Did you select the option to install the package? (not enabled by default)

**Comment by cdeil** [comment]
@astrofrog - Thanks for the tip. That was the issue.

Now I'm getting this:
https://readthedocs.org/projects/healpix/builds/4372859/
```
error: [Errno 2] Could not find C/C++ file healpix/raw/wrap.(c/cpp) for Cython file healpix/raw/wrap.pyx when building extension healpix.raw.wrap. Cython must be installed to build from a git checkout.: 'healpix/raw/wrap.c'
```

I guess I have to add the requirements file for RTD with Cython added, there's no other way, right?

**Comment by cdeil** [comment]
OK, now I'm trying to do it with conda: 30587bc

**Comment by cdeil** [comment]
With #3 merged, the docs build is now working on RTD:
http://healpix.readthedocs.io/en/latest/

@astrofrog - Thanks for the help.
